console.log('🔄 Para aplicar as novas rotas de configuração do app:');
console.log('');
console.log('1. Pare o servidor atual (Ctrl+C)');
console.log('2. Execute: node index_quiz_educativo.js');
console.log('');
console.log('📋 Rotas disponíveis após reiniciar:');
console.log('   GET  /api/app-settings     - Buscar configurações');
console.log('   PUT  /api/app-settings     - Atualizar configurações');
console.log('   GET  /api/health           - Status do servidor');
console.log('   GET  /api/quiz             - Listar quizzes');
console.log('');
console.log('🧪 Para testar as configurações:');
console.log('   node test_app_settings.js  - Testar banco de dados');
console.log('   node add_app_settings.js   - Criar tabela se necessário');
console.log('');
console.log('📱 No app mobile:');
console.log('   - As configurações padrão serão usadas se o servidor estiver offline');
console.log('   - Toque no botão ⚙️ para acessar as configurações');
console.log('   - Todas as mudanças são salvas localmente mesmo offline');